import type { Dictionary } from "./pt";

/**
 * English dictionary. Typed against the Portuguese one — if a key is added to
 * pt.ts and not here, this file stops compiling.
 */

const en: Dictionary = {
  meta: {
    title: "Arthur Henrique Tachini · Software Engineer",
    description:
      "Software Engineer based in Joinville, Brazil. PHP and Laravel on the back end, Vue and React on the front. End-to-end web applications and landing pages.",
    ogRole: "Software Engineer",
  },

  nav: {
    skipToContent: "Skip to content",
    languageLabel: "Language",
    themeLabel: "Switch between light and dark theme",
    cableLabel: "Page sections",
    sections: {
      about: "About",
      stack: "Stack",
      timeline: "Trajectory",
      projects: "Projects",
      testimonials: "Recommendations",
      contact: "Contact",
    },
  },

  hero: {
    role: "Software Engineer",
    location: "Joinville · BR",
    lede: "I build web applications end to end: PHP and Laravel on the back, Vue and React on the front. During the day that means enterprise software at SoftExpert. Outside it, landing pages and digital presence for people who need to exist properly online.",
    clockLabel: "Local time",
    photoAlt: "Arthur Henrique Tachini, in glasses and a black jumper, looking off frame",
    scrollHint: "Scroll",
  },

  about: {
    eyebrow: "About",
    title: "How I work",
    paragraphs: [
      "I started with the Senai technical course in 2020 and entered the industry in 2022 at FACE Digital, where I moved from trainee to junior full stack working on Laravel projects applying SOLID and DDD, Vue on the front, MongoDB and Oracle underneath. I also helped bring up the developers who arrived after me.",
      "Since 2024 I have been a Software Engineer at SoftExpert. I started on the OnDemand team, building external PHP applications that customised the company's suite and writing the SQL behind them. I am now on APS — Archival, Protocol and Storeroom, core components of the SoftExpert Suite — where I led the implementation of the team's automated testing infrastructure.",
      "That last part became my final thesis at Univille: a comparison between unit tests written by hand and unit tests generated by artificial intelligence.",
    ],
    meta: {
      sinceLabel: "In the field since",
      experienceLabel: "Years of experience",
      cityLabel: "Based in",
      cityValue: "Joinville, Brazil",
      degreeLabel: "Degree",
      degreeValue: "Software Engineering, Univille",
      languagesLabel: "Languages",
      languagesValue: "Portuguese native · English intermediate",
    },
  },

  stack: {
    eyebrow: "Stack",
    title: "Tools, and where they were actually used",
    hint: "Hover a row to see where each one was actually used.",
    hintTouch: "Tap a row to see where each one was actually used.",
    groups: {
      languages: "Languages",
      backend: "Back end",
      frontend: "Front end",
      data: "Data",
      infra: "Infrastructure",
      quality: "Quality",
    },
    places: {
      personal: "Personal projects",
    },
  },

  timeline: {
    eyebrow: "Trajectory",
    title: "From 2020 to here",
    present: "now",
    trackLabels: {
      education: "Study",
      work: "Work",
    },
    items: {
      senai: {
        role: "Technical Diploma, Systems Development",
        summary: "Technical training in systems development.",
      },
      "face-trainee": {
        role: "Trainee Developer",
        summary:
          "PHP and Laravel day to day, Docker in the environment. Helped bring up the developers who arrived after me.",
      },
      univille: {
        role: "Software Engineering",
        summary: "Degree completed in July 2026.",
      },
      "face-junior": {
        role: "Junior Full Stack Developer",
        summary:
          "More complex web projects: Laravel applying SOLID and DDD, Vue on the front, MongoDB and Oracle underneath.",
      },
      "softexpert-php": {
        role: "PHP Developer",
        summary:
          "On the OnDemand team: external PHP applications customising the suite, and the SQL queries behind them.",
      },
      "softexpert-aps": {
        role: "Software Engineer I",
        summary:
          "On the APS team (Archival, Protocol and Storeroom), where I worked as a full stack developer and led the team's automated testing infrastructure.",
      },
      tcc: {
        role: "Final thesis",
        summary:
          "A comparison between unit tests written by hand and unit tests generated by artificial intelligence.",
      },
    },
  },

  projects: {
    eyebrow: "Projects",
    title: "What I have built",
    featuredLabel: "Featured",
    yearLabel: "Year",
    roleLabel: "Role",
    techLabel: "Stack",
    open: "Open",
    close: "Close",
    repo: "Repository",
    demo: "Demo",
    items: {
      "patos-digitais": {
        role: "Author",
        description:
          "A social network built to give people a free space for interaction and exchanging experiences.",
      },
      "o-patusco": {
        role: "Author",
        description:
          "A veterinary clinic platform where owners register their pets and book appointments.",
      },
      "autostock-manager": {
        role: "Author",
        description:
          "A vehicle sales management platform with multiple users and permission levels. Vue on the front, a separate Java and Spring Boot API behind it.",
      },
      "semente-solidaria": {
        role: "Author",
        description:
          "A community initiative supporting families in difficult circumstances, with stock control over a donations depot.",
      },
      miranda: {
        role: "Author",
        description:
          "Personal project: an application using artificial intelligence to suggest daily outfits.",
      },
      "i-love-my-duck": {
        role: "Author",
        description:
          "A web application that splits videos into parts for posting as stories. All processing happens in the browser.",
      },
    },
  },

  testimonials: {
    eyebrow: "Recommendations",
    title: "People who worked with me",
    // These are quoted verbatim, and the people who wrote them wrote them in
    // Portuguese. Translating somebody's recommendation would be attributing
    // sentences to them that they never wrote, so the reader is told instead.
    note: "Quoted in the original Portuguese, as written.",
    people: {
      "matheus-hagedorn": { relation: "University classmate" },
      "giordano-gava": { relation: "University classmate" },
      "walter-coan": { relation: "Professor at Univille" },
      "thiago-rodrigues": { relation: "Colleague" },
      "matheus-bittencourt": { relation: "Colleague" },
    },
  },

  contact: {
    eyebrow: "Contact",
    title: "Tell me what you need built",
    lede: "A role, a freelance project, or an open-ended conversation: all three land in the same place.",
    emailLabel: "Email",
    copy: "Copy",
    copied: "Copied",
    copyFailed: "Copying failed. Select the address above instead.",
    form: {
      name: "Name",
      email: "Email",
      message: "Message",
      submit: "Send",
      sending: "Sending",
    },
    validation: {
      name: "Write your name.",
      email: "That email does not look valid.",
      message: "Write your message.",
      messageShort: "Write a little more. At least ten characters.",
    },
    states: {
      success: "Message sent. I reply within two working days.",
      error: "Sending failed. Write directly to arthurtachini.dev@gmail.com.",
      notConfigured:
        "The form is not connected yet. Write directly to arthurtachini.dev@gmail.com.",
    },
  },

  footer: {
    navLabel: "Navigation",
    socialLabel: "Where to find me",
    contactLabel: "Direct contact",
    backToTop: "Back to top",
  },
};

export default en;
